=== vmermolenko/JAVA-IT-Academy/XML/Resource/family_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.example.org/family_schema" 
           xmlns:tns="http://www.example.org/family_schema" elementFormDefault="qualified">

	<xs:element name="families">
		<xs:complexType>
			<xs:sequence>
			<xs:element name="family" maxOccurs="unbounded" minOccurs="1" type="tns:family_type"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="family_type">
		<xs:sequence>
			<xs:element name="mother" type="tns:mother_type"/>	
			<xs:element name="father" type="tns:father_type"/>	
			<xs:element name="children" type="tns:children_type"/>	
		</xs:sequence>
		<xs:attribute name="address" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="mother_type">
	    <xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="surname" type="xs:string"/>
			<xs:element name="age" type="xs:int"/>
			<xs:element name="hobby">
				<xs:complexType>
				   <xs:sequence>
				      <xs:element name="title" type="xs:string"/>
				      <xs:element name="times-per-week" type="xs:string"/>
				      <xs:element name="schedule">
				      	  <xs:complexType>
						      <xs:sequence  maxOccurs="unbounded" minOccurs="2">
						   		  <xs:element name="day" type="xs:string"/>
						   		  <xs:element name="time" type="xs:string"/>
						      </xs:sequence>
						  </xs:complexType>
				      </xs:element>
				   </xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="father_type">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="surname" type="xs:string"/>
			<xs:element name="age" type="xs:int"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="children_type">
		<xs:sequence>
			<xs:element name="child"  maxOccurs="unbounded" minOccurs="1" type="tns:child_type"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="child_type">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="surname" type="xs:string"/>
			<xs:element name="age" type="xs:int"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== vmermolenko/JAVA-IT-Academy/XML/Resource/family.xml
<?xml version="1.0" encoding="UTF-8"?>
<families xmlns="http://www.example.org/family_schema"
		  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		  xsi:schemaLocation="http://www.example.org/family_schema family_schema.xsd">

	<family address="Sts Belarus Minsk â„–111">
		<mother>
			<name>Elena</name>
			<surname>Ivanova</surname>
			<age>30</age>
		</mother>
		
		<father>
			<name>Ivan</name>
			<surname>Ivanov</surname>
			<age>33</age>
		</father>
	  
		<children>
			<child>
				<name>Ivan</name>
				<surname>Ivanov</surname>
				<age>10</age>
			</child>
			<child>
				<name></name>
				<surname></surname>
				<age>10</age>
			</child>
			<child>
				<name></name>
				<surname></surname>
				<age>33</age>
			</child>
			<child>
				<name></name>
				<surname></surname>
				<age>33</age>
			</child>

		</children>
		
		
	</family>

</families>
